### ISSUE TITLE
Remove RFN

### ISSUE THREAD

**Issue by davelab6** [nclm/susan#1]
I suggest to remove the RFN from https://github.com/nclm/susan/blob/master/COPYRIGHT.txt#L1

A reserved font name isn't a good idea for 2 reasons.
1. It makes the process of collaboration via github cumbersome; if a member
   of the general public clicks the 'fork' button up top right, they must
   either seek permission from you before-hand to use the RFN, or to
   immediately change the font name in the files as part of their first
   modification, and then you'll have to change it back.
2. Many websites who self host the font files will modify them, doing
   subsetting and format conversion, which are both explicitly defined in the
   OFL as kinds of modification subject to the RFN restriction. SIL have been
   willing to offer their view that the most popular web font formats are not
   format conversions subject to the RFN restriction, but popular web font
   bundling service Font Squirrel includes the less popular formats too, which
   do. And subsetting remains. So, changing the name or contacting you are
   both administrative burdens for these downstream users, and if they do
   contact you, for you; and many people won't think carefully about this and
   will just do so without asking, which formally terminates their license.
   Putting them in that position is not a good situation.

So not having any RFNs is my first preference. I look forward to hearing
your view :)

**Comment by nclm** [comment]
Hey, thanks for your advice! :)

I did not know RFN was optional, but was indeed wondering how it could work for collaboration. Thank you for telling me about these issues! I went to read the OFL FAQ again afterwards, and well, I prefer without it, too. I’m removing it now.

Do you know how the copyright header/file works otherwise? Should all contributors add their names and a date?

**Comment by nclm** [comment]
Closing the first issue! :)
(of a font that is not even published yet, haha)

**Comment by davelab6** [comment]
> I did not know RFN was optional, but was indeed wondering how it could work for collaboration. Thank you for telling me about these issues! I went to read the OFL FAQ again afterwards, and well, I prefer without it, too. I’m removing it now.

Great!

> Do you know how the copyright header/file works otherwise? Should all contributors add their names and a date?

Yes. I set up this project following the Google Open Source Project Office's standard advice:
- https://github.com/googlefonts/fontbakery/blob/master/AUTHORS.txt
- https://github.com/googlefonts/fontbakery/blob/master/CONTRIBUTORS.txt
- https://github.com/googlefonts/fontbakery/blob/master/LICENSE.txt

https://github.com/nclm/susan/blob/master/COPYRIGHT.txt#L3 should also be removed I think, belongs in the README.

**Comment by nclm** [comment]
> the Google Open Source Project Office's standard advice

Thanks!
I’d be using (approximately) [Unified Font Repository](https://github.com/raphaelbastide/Unified-Font-Repository) as a structure, so `COPYRIGHT.txt` is my `AUTHORS.txt` and the last section of `FONTLOG.txt` my `CONTRIBUTORS.txt`.

If I get it, every contributors should add their names both as authors (= copyright holders) and contributors, except if they contribute for the account of a company, in which case the company is listed as a holder instead?

> L3 should also be removed I think, belongs in the README.

Right! I wasn’t sure, as the design is not completely original, how to credit it in a legal way. I was planning to write more about the original in `README` or `FONTLOG` any way.

**Comment by davelab6** [comment]
> I’d be using (approximately) Unified Font Repository as a structure, so COPYRIGHT.txt is my AUTHORS.txt and the last section of FONTLOG.txt my CONTRIBUTORS.txt.

Yes, that sounds right to me.

> If I get it, every contributors should add their names both as authors (= copyright holders) and contributors, except if they contribute for the account of a company, in which case the company is listed as a holder instead?

Yes

> > L3 should also be removed I think, belongs in the README.
> 
> Right! I wasn’t sure, as the design is not completely original, how to credit it in a legal way. I was planning to write more about the original in README or FONTLOG any way.

This is not legal advice: The design credits are "moral rights" and they are different to copyrights. In most places the design itself isn't subject to copyright restrictions, only the digital data is.

**Comment by nclm** [comment]
> The design credits are "moral rights" and they are different to copyrights. In most places the design itself isn't subject to copyright restrictions, only the digital data is.

Of course, I knew about this at one point! Thanks for reminding me of the difference :)
I’ll edit this in a future commit.

Thank you for all your comments!
